fix(ktlint): format everything

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -1,52 +1,52 @@
 name: Java CI with Gradle
 
 on:
-  push:
-    branches: [ "main", "release/*" ]
-  pull_request:
-    branches: [ "main", "release/*" ]
-  schedule:
-    - cron: "0 8 * * 2"
+    push:
+        branches: [ "main", "release/*" ]
+    pull_request:
+        branches: [ "main", "release/*" ]
+    schedule:
+        -   cron: "0 8 * * 2"
 
 permissions:
-  contents: read
-  checks: write
-  pull-requests: write
+    contents: read
+    checks: write
+    pull-requests: write
 
 jobs:
-  build-gradle-project:
-    runs-on: ubuntu-latest
+    build-gradle-project:
+        runs-on: ubuntu-latest
 
-    steps:
-      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
-        with:
-          fetch-depth: 0
-      - name: Set up JDK 21
-        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
-        with:
-          java-version: '21'
-          distribution: 'temurin'
-      - name: Cache SonarQube packages
-        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
-        with:
-          path: ~/.sonar/cache
-          key: ${{ runner.os }}-sonar
-          restore-keys: ${{ runner.os }}-sonar
-      - name: Cache Playwright browsers
-        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
-        with:
-          path: ~/.cache/ms-playwright
-          key: ${{ runner.os }}-playwright-${{ hashFiles('**/gradle/libs.versions.toml') }}
-          restore-keys: ${{ runner.os }}-playwright
-      - name: Setup Gradle
-        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0
-      - name: Execute Gradle build
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
-        run: ./gradlew build testCodeCoverageReport sonar -x check --info # TODO: remove the -x check to have a merge quality gate (only after everything is green :)
-      - name: Publish Test Report
-        uses: mikepenz/action-junit-report@e08919a3b1fb83a78393dfb775a9c37f17d8eea6 # v6.0.1
-        if: success() || failure() # always run even if the previous step fails
-        with:
-          report_paths: '**/build/test-results/test/TEST-*.xml'
+        steps:
+            -   uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
+                with:
+                    fetch-depth: 0
+            -   name: Set up JDK 21
+                uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5.1.0
+                with:
+                    java-version: '21'
+                    distribution: 'temurin'
+            -   name: Cache SonarQube packages
+                uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
+                with:
+                    path: ~/.sonar/cache
+                    key: ${{ runner.os }}-sonar
+                    restore-keys: ${{ runner.os }}-sonar
+            -   name: Cache Playwright browsers
+                uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
+                with:
+                    path: ~/.cache/ms-playwright
+                    key: ${{ runner.os }}-playwright-${{ hashFiles('**/gradle/libs.versions.toml') }}
+                    restore-keys: ${{ runner.os }}-playwright
+            -   name: Setup Gradle
+                uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5.0.0
+            -   name: Execute Gradle build
+                env:
+                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+                    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+                run: ./gradlew build testCodeCoverageReport sonar -x check --info # TODO: remove the -x check to have a merge quality gate (only after everything is green :)
+            -   name: Publish Test Report
+                uses: mikepenz/action-junit-report@e08919a3b1fb83a78393dfb775a9c37f17d8eea6 # v6.0.1
+                if: success() || failure() # always run even if the previous step fails
+                with:
+                    report_paths: '**/build/test-results/test/TEST-*.xml'
